eventhub_import.settings:
  type: config_object
  label: 'EventHub settings'
  mapping:
    api_endpoint:
      type: string
      label: 'API endpoint'
    import_batch_size:
      type: integer
      label: 'Import batch size'
    notification_email:
      type: string
      label: 'Notification email'
