<?php

/**
 * @file
 * Provides an eventhub entity example entity type.
 */

declare(strict_types=1);

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function eventhub_entity_example_theme(): array {
  return [
    'event_example' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for eventexample templates.
 *
 * Default template: event-example.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the eventexample information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_event_example(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function eventhub_entity_example_user_cancel(array $edit, UserInterface $account, string $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish eventexamples.
      $storage = \Drupal::entityTypeManager()->getStorage('event_example');
      $event_example_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      /** @var \Drupal\eventhub_entity_example\Entity\EventExample $event_example */
      foreach ($storage->loadMultiple($event_example_ids) as $event_example) {
        $event_example->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize eventexamples.
      $storage = \Drupal::entityTypeManager()->getStorage('event_example');
      $event_example_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      /** @var \Drupal\eventhub_entity_example\Entity\EventExample $event_example */
      foreach ($storage->loadMultiple($event_example_ids) as $event_example) {
        $event_example->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function eventhub_entity_example_user_predelete(UserInterface $account): void {
  // Delete eventexamples that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('event_example');
  $event_example_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($event_example_ids)
  );
}
